/**
 * generated by Xtext
 */
package fr.inria.atlanmod.neoemf.ui.contentassist;

import fr.inria.atlanmod.neoemf.ui.contentassist.AbstractPrefetchingProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class PrefetchingProposalProvider extends AbstractPrefetchingProposalProvider {
}
