/*
* generated by Xtext
*/
package fr.inria.atlanmod.neoemf.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import fr.inria.atlanmod.neoemf.services.PrefetchingGrammarAccess;

public class PrefetchingParser extends AbstractContentAssistParser {
	
	@Inject
	private PrefetchingGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected fr.inria.atlanmod.neoemf.ui.contentassist.antlr.internal.InternalPrefetchingParser createParser() {
		fr.inria.atlanmod.neoemf.ui.contentassist.antlr.internal.InternalPrefetchingParser result = new fr.inria.atlanmod.neoemf.ui.contentassist.antlr.internal.InternalPrefetchingParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getCacheTypeAccess().getAlternatives(), "rule__CacheType__Alternatives");
					put(grammarAccess.getRefTypeAccess().getAlternatives(), "rule__RefType__Alternatives");
					put(grammarAccess.getMomentAccess().getAlternatives(), "rule__Moment__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getMetamodelImportAccess().getGroup(), "rule__MetamodelImport__Group__0");
					put(grammarAccess.getCacheAccess().getGroup(), "rule__Cache__Group__0");
					put(grammarAccess.getCachePropertiesAccess().getGroup(), "rule__CacheProperties__Group__0");
					put(grammarAccess.getPlanAccess().getGroup(), "rule__Plan__Group__0");
					put(grammarAccess.getAfterRuleAccess().getGroup(), "rule__AfterRule__Group__0");
					put(grammarAccess.getPrefetchingRuleAccess().getGroup(), "rule__PrefetchingRule__Group__0");
					put(grammarAccess.getPrefetchingRuleAccess().getGroup_4(), "rule__PrefetchingRule__Group_4__0");
					put(grammarAccess.getPrefetchingRuleAccess().getGroup_5(), "rule__PrefetchingRule__Group_5__0");
					put(grammarAccess.getSourcePatternAccess().getGroup(), "rule__SourcePattern__Group__0");
					put(grammarAccess.getFilterPatternAccess().getGroup(), "rule__FilterPattern__Group__0");
					put(grammarAccess.getTargetPatternAccess().getGroup(), "rule__TargetPattern__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getModelAccess().getMetamodelAssignment_0(), "rule__Model__MetamodelAssignment_0");
					put(grammarAccess.getModelAccess().getCacheAssignment_1(), "rule__Model__CacheAssignment_1");
					put(grammarAccess.getModelAccess().getPlansAssignment_2(), "rule__Model__PlansAssignment_2");
					put(grammarAccess.getMetamodelImportAccess().getNsURIAssignment_1(), "rule__MetamodelImport__NsURIAssignment_1");
					put(grammarAccess.getCacheAccess().getTypeAssignment_1(), "rule__Cache__TypeAssignment_1");
					put(grammarAccess.getCacheAccess().getPropertiesAssignment_2(), "rule__Cache__PropertiesAssignment_2");
					put(grammarAccess.getCachePropertiesAccess().getRefTypeAssignment_2(), "rule__CacheProperties__RefTypeAssignment_2");
					put(grammarAccess.getCachePropertiesAccess().getSizeAssignment_4(), "rule__CacheProperties__SizeAssignment_4");
					put(grammarAccess.getPlanAccess().getPlanIdAssignment_1(), "rule__Plan__PlanIdAssignment_1");
					put(grammarAccess.getPlanAccess().getAfterAssignment_2(), "rule__Plan__AfterAssignment_2");
					put(grammarAccess.getPlanAccess().getRulesAssignment_4(), "rule__Plan__RulesAssignment_4");
					put(grammarAccess.getAfterRuleAccess().getPlanIdAssignment_1(), "rule__AfterRule__PlanIdAssignment_1");
					put(grammarAccess.getPrefetchingRuleAccess().getMomentAssignment_0(), "rule__PrefetchingRule__MomentAssignment_0");
					put(grammarAccess.getPrefetchingRuleAccess().getSourcePatternAssignment_1(), "rule__PrefetchingRule__SourcePatternAssignment_1");
					put(grammarAccess.getPrefetchingRuleAccess().getTargetPatternAssignment_3(), "rule__PrefetchingRule__TargetPatternAssignment_3");
					put(grammarAccess.getPrefetchingRuleAccess().getProbabilityAssignment_4_0(), "rule__PrefetchingRule__ProbabilityAssignment_4_0");
					put(grammarAccess.getPrefetchingRuleAccess().getSubRulesAssignment_5_1(), "rule__PrefetchingRule__SubRulesAssignment_5_1");
					put(grammarAccess.getSourcePatternAccess().getPatternAssignment_0(), "rule__SourcePattern__PatternAssignment_0");
					put(grammarAccess.getSourcePatternAccess().getFilterAssignment_1(), "rule__SourcePattern__FilterAssignment_1");
					put(grammarAccess.getFilterPatternAccess().getStringPatternAssignment_1(), "rule__FilterPattern__StringPatternAssignment_1");
					put(grammarAccess.getTargetPatternAccess().getPatternAssignment_0(), "rule__TargetPattern__PatternAssignment_0");
					put(grammarAccess.getTargetPatternAccess().getFilterAssignment_1(), "rule__TargetPattern__FilterAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			fr.inria.atlanmod.neoemf.ui.contentassist.antlr.internal.InternalPrefetchingParser typedParser = (fr.inria.atlanmod.neoemf.ui.contentassist.antlr.internal.InternalPrefetchingParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public PrefetchingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PrefetchingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
