/*
 * generated by Xtext
 */
package fr.inria.atlanmod.neoemf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.linking.lazy.LazyLinker;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PrefetchingUiModule extends fr.inria.atlanmod.neoemf.ui.AbstractPrefetchingUiModule {
	public PrefetchingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration () {
	     return PrefetchingHighlightingConfiguration.class;
	}
	
	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return PrefetchingAntlrTokenToAttributeIdMapper.class;
	}
	
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return PrefetchingSemanticHighlightingCalculator.class;
	}
	
	public Class<? extends LazyLinker> bindLazyLinker() {
		return PrefetchingLazyLinker.class;
	}
	
	public Class<? extends IEObjectHoverProvider> bindIEobjectHoverProvider() {
		return PrefetchingEObjectHoverProvider.class;
	}
	
	public Class<? extends IEObjectDocumentationProvider> bindIEobjectDocumentationProvider() {
		return PrefetchingEObjectDocumentationProvider.class;
	}
	
}
