/*
 * generated by Xtext
 */
package fr.inria.atlanmod.neoemf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PrefetchingUiModule extends fr.inria.atlanmod.neoemf.ui.AbstractPrefetchingUiModule {
	public PrefetchingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
