/*
* generated by Xtext
*/
package fr.inria.atlanmod.neoemf;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PrefetchingStandaloneSetup extends PrefetchingStandaloneSetupGenerated{

	public static void doSetup() {
		new PrefetchingStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

