/*
 * generated by Xtext
 */
package fr.inria.atlanmod.neoemf;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PrefetchingRuntimeModule extends fr.inria.atlanmod.neoemf.AbstractPrefetchingRuntimeModule {

}
