/*
 * generated by Xtext
 */
package fr.inria.atlanmod.neoemf.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.inria.atlanmod.neoemf.ui.internal.PrefetchingActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PrefetchingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PrefetchingActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PrefetchingActivator.getInstance().getInjector(PrefetchingActivator.FR_INRIA_ATLANMOD_NEOEMF_PREFETCHING);
	}
	
}
