/*
* generated by Xtext
*/
package fr.inria.atlanmod.neoemf.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.inria.atlanmod.neoemf.services.PrefetchingGrammarAccess;

public class PrefetchingParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PrefetchingGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.inria.atlanmod.neoemf.parser.antlr.internal.InternalPrefetchingParser createParser(XtextTokenStream stream) {
		return new fr.inria.atlanmod.neoemf.parser.antlr.internal.InternalPrefetchingParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public PrefetchingGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PrefetchingGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
