/*
* generated by Xtext
*/
package fr.inria.atlanmod.neoemf.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PrefetchingAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/inria/atlanmod/neoemf/parser/antlr/internal/InternalPrefetching.tokens");
	}
}
