/*
* generated by Xtext
*/
package fr.inria.atlanmod.neoemf;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PrefetchingUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.inria.atlanmod.neoemf.ui.internal.PrefetchingActivator.getInstance().getInjector("fr.inria.atlanmod.neoemf.Prefetching");
	}
	
}
