/*
 * generated by Xtext
 */
package fr.inria.atlanmod.prefetchml.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PrefetchMLRuntimeModule extends fr.inria.atlanmod.prefetchml.language.AbstractPrefetchingRuntimeModule {

}
