/*
* generated by Xtext
*/
package fr.inria.atlanmod.prefetchml.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PrefetchMLStandaloneSetup extends PrefetchingStandaloneSetupGenerated {

	public static void doSetup() {
		new PrefetchMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

