/**
 * generated by Xtext
 */
package fr.inria.atlanmod.neoemf.validation;

import fr.inria.atlanmod.neoemf.validation.AbstractPrefetchingValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class PrefetchingValidator extends AbstractPrefetchingValidator {
}
